/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Conditions } from './conditions';
import { Operand } from './operand';

export interface BinaryCondition extends Conditions { 
    left?: Operand;
    operator?: BinaryCondition.OperatorEnum;
    right?: Operand;
}
export namespace BinaryCondition {
    export type OperatorEnum = 'EQUAL' | 'NOT_EQUAL' | 'GREATER' | 'LOWER' | 'LOWER_EQUAL' | 'GREATER_EQUAL';
    export const OperatorEnum = {
        EQUAL: 'EQUAL' as OperatorEnum,
        NOTEQUAL: 'NOT_EQUAL' as OperatorEnum,
        GREATER: 'GREATER' as OperatorEnum,
        LOWER: 'LOWER' as OperatorEnum,
        LOWEREQUAL: 'LOWER_EQUAL' as OperatorEnum,
        GREATEREQUAL: 'GREATER_EQUAL' as OperatorEnum
    };
}