/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ActionParamResponseDTO { 
    paramName?: string;
    paramType?: string;
    paramDirection?: ActionParamResponseDTO.ParamDirectionEnum;
}
export namespace ActionParamResponseDTO {
    export type ParamDirectionEnum = 'ActionParamDirection.INPUT' | 'ActionParamDirection.OUTPUT';
    export const ParamDirectionEnum = {
        INPUT: 'INPUT' as ParamDirectionEnum,
        OUTPUT: 'OUTPUT' as ParamDirectionEnum
    };
}
