/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Operand { 
    type?: Operand.TypeEnum;
}
export namespace Operand {
    export type TypeEnum = 'FACT_FIELD' | 'FIXED_VALUE';
    export const TypeEnum = {
        FACTFIELD: 'FACT_FIELD' as TypeEnum,
        FIXEDVALUE: 'FIXED_VALUE' as TypeEnum
    };
}